### ISSUE TITLE
Accept Header does not contain api-version.

### ISSUE THREAD

**Issue by papauorg** [scrumdod/hubot-vsonline#19]
Hi,

I am trying to get this hubot plugin running against a on premise TFS2015.

The authentication and retrieval of user info and rooms is working properly but when hubot tries to connect to a room I get the following error message on the console:

> INFO Failed to join room with status 400

I had a look at the server logs, the URI that was requested is ok, but the accept header does not contain the api-version. I used postman to test the url with and without the accept header and if I included it, it worked properly. 
The serverlog also shows that the retrieval of users sends the request with the correct accept header. Only the put operation to join a room does not include it (I don't know about others, I can't get further than the joining a room part).

Snipped from the server log:

> # Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken Content-Type Accept
> 
> 2015-07-07 16:33:24 10.49.13.227 GET /_apis/chat/rooms - 80 user@mydomain.com 10.49.56.244 vso-client/1.0+node/0.10.25+linux - 200 0 0 21 application/json application/json;+api-version=1.0
> 2015-07-07 16:33:24 10.49.13.227 GET /_apis/connectionData - 80 user@mydomain.com 10.49.56.244 vso-client/1.0+node/0.10.25+linux - 200 0 0 15 application/json application/json;+api-version=1.0
> 2015-07-07 16:33:24 10.49.13.227 PUT /_apis/chat/rooms/4/users/cddfa03f-b91f-480d-932e-d5986a69d718 - 80 user@mydomain.com 10.49.56.244 request-json/1.0 - 400 0 0 75 application/json application/json
> 2015-07-07 16:33:24 10.49.13.227 GET /_apis/chat/rooms/4/users - 80 user@mydomain.com 10.49.56.244 vso-client/1.0+node/0.10.25+linux - 200 0 0 113 application/json application/json;+api-version=1.0

Hubot runs on a Ubuntu machine 14.04
node version: 0.10.25
hubot-vsonline version: 0.2.9 (via npm install)

Any idea how I can get around this issue?

**Comment by bfcamara** [comment]
Hi @papauorg,

it seems an issue. Could you check what vso-client version is being installed with hubot-vsonline? I'm gonna try to repro.

However, this shouldn't be preventing you to continue - you just won't be able to see the user presence in the room  - but you should still be able to issue/receive commands.

One more thing, are you hosting your TFS instsance in a vdir? There are some known issues in hubot-vsonline/vso-client when targeting TFS hosted in a vdir like http://machinename:8080/tfs.

**Comment by bfcamara** [comment]
I've managed to repro the problem. 

@reverentgeek The issue is in the vso-client module in method joinRoom when invoking the put method the arguments order is not correct.

Need to file an issue in vso-client.

Good catch!

**Comment by bfcamara** [comment]
@papauorg You can update vso-client to version 0.2.5

```
npm update vso-client
```

Thank you @reverentgeek for the quick fix.

**Comment by papauorg** [comment]
That was real quick :). I didn't even get the chance to answer your questions.

@bfcamara that was it. Thanks for your help.
@reverentgeek, thanks for fixing.

For the sake of completeness: vso-client was version 0.2.4. And we also changed the vdir hosting to use the site root before.

After the update to vso-client 0.2.5 hubot connects successfully.
Thank you guys
